"""empty message

Revision ID: 082a355952bb
Revises: ceeab85d9f63
Create Date: 2025-06-13 16:07:59.119084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082a355952bb'
down_revision = 'ceeab85d9f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
