"""empty message

Revision ID: e6174c7c1da8
Revises: 6830d2b97a75
Create Date: 2025-06-12 16:58:20.604720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6174c7c1da8'
down_revision = '6830d2b97a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('song_owner_id_fkey'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('song_owner_id_fkey'), 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###
