"""empty message

Revision ID: f3f455e9468c
Revises: e6174c7c1da8
Create Date: 2025-06-13 15:08:43.042802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f455e9468c'
down_revision = 'e6174c7c1da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('album',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('song_subtitle_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('song_title_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('song_title_key'), ['title'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('song_subtitle_key'), ['subtitle'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('album',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
